version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bikerental-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bikerental
      MYSQL_USER: bikerentaluser
      MYSQL_PASSWORD: bikerentalpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/bikerental.sql:/docker-entrypoint-initdb.d/bikerental.sql
    networks:
      - bikerental-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - bikerental-network

networks:
  bikerental-network:

volumes:
  db_data:
